### ISSUE TITLE
Rename branches according to git-flow

### ISSUE THREAD

**Issue by thebao** [Steinbloum/Martingale#10]
In accordance with git-flow workflow, renaming branches as follows:

`main` becomes `master`
`Neat` beacomes `develop`

All features are prefixed with `feature/`.

For more info cf. [git-flow documentation](https://danielkummer.github.io/git-flow-cheatsheet/)

**Comment by thebao** [comment]
i don't have sufficient permission to remove the `main` branch as it is the default branch - you can [change the default branch](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/changing-the-default-branch#about-changing-the-default-branch) to `master` inside the project settings. However, I recommend using `develop` which doesn't exist yet. We can discuss this on the phone.

Adding `help wanted` label and assigning to @Steinbloum as this is a **blocking issue**. It is not urgent however, I'd say medium priority.

**Comment by Steinbloum** [comment]
Done. 
J'ai été obligé de supprimer la branch neat mais j'ai fait une develop en local, j'ai merge neat dessus et j'ai push develop. Par contre il m'a pas proposé de commit donc j'ai pas pu commenter. C'est parce que on peut que commit des changements dans des fichiers pas des les structures je présume

**Comment by thebao** [comment]
*p r o p r e*
