### ISSUE TITLE
HALP

### ISSUE THREAD

**Issue by Steinbloum** [Steinbloum/Martingale#12]
j'arrive plus rien à ouvrir, j'ai la chose suivante dans la console pycham 👍 C:\Users\astei\AppData\Local\Programs\Python\Python39\python.exe C:/dev/Martingale2/main.py
Traceback (most recent call last):
  File "C:\dev\Martingale2\main.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\astei\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "C:\Users\astei\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\cbook\__init__.py", line 28, in <module>
    import numpy as np
  File "C:\Users\astei\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\astei\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\astei\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

Process finished with exit code 1

et quand j'essaye de run avec le python interpreter normal ça s'ouvre et ça se ferme tout de suite. Qualeaue chose a voir avec le virtual env dont tu me parlais? ya un setting qui s'est glissé avec un pull ? 
halp

**Comment by thebao** [comment]
This seems to be a Windows related issue: 
cf. https://stackoverflow.com/questions/64729944/runtimeerror-the-current-numpy-installation-fails-to-pass-a-sanity-check-due-to

I've frozen the `numpy` dependency in `requirements.txt` to `1.19.3`. Can you try:
- checking out `master` branch with `git checkout master`
- pulling changes with `git pull`
- activating the virtualenv with `source env/bin/activate`
- reinstalling dependencies with `pip install -r requirements.txt`
- running the app with `python main.py`

and check if that solves the problem

**Comment by Steinbloum** [comment]
Ok setup Venv done, it works. issue was it was searchong for pyhton interpreter in main project dir instead of where i put it

nevertheless (Thanks lvl2 CSI) 
 whenever i checkout master branch from remote it make a new worskpace and i cannot find git functions in it. is there an associated workspace with master branch ? still figuring out pycham

**Comment by thebao** [comment]
i'm not familiar with PyCharm so I'm afraid I can't be much of much on this issue.

You can try;
https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html#python_create_virtual_env
or
https://www.jetbrains.com/help/pycharm/manage-branches.html#checkout-Git-branch

or you can just manage your environment from the command line and avoid the JetBrains/PyCharm interference 😛
